### ISSUE TITLE
[improvement] Allow overriding default serializer used in to_value

### ISSUE THREAD

**Issue by JorritSalverda** [RReverser/serde-wasm-bindgen#60]
Cloudflare's Queue and Key Value implementations rely on this crate. But they both use the default serializer because of their usage of to_value:

- https://github.com/cloudflare/workers-rs/blob/c57f7a6d31da601397e46daec5a9448d6efbe1cc/worker/src/queue.rs#L184
- https://github.com/zebp/worker-kv/blob/3c53503d21248b0b00ac3d7802a94848f2e22178/src/builder.rs#L49

It would be nice if the `Serializer::new()` used in https://github.com/RReverser/serde-wasm-bindgen/blob/main/src/lib.rs#L77-L80 could return an overridable serializer. This can be done using a mutable static.

**Comment by RReverser** [comment]
It's not a good idea to change global state in ways that will affect all 3rd-party code in non-obvious and, likely, breaking ways.

If you want those libraries to use a different or configurable serializer, it's better to add that to libraries themselves.
