### ISSUE TITLE
Can't figure out how to get Option<js_sys::Date> to work when serializing to JS

### ISSUE THREAD

**Issue by ronnybremer** [RReverser/serde-wasm-bindgen#62]
I have a struct containing a js_sys::Date field, which works perfectly with the `preserve` module:

```rust
pub struct Params {
    #[serde(
        skip_deserializing,
        default = "js_sys::Date::new_0",
        with = "serde_wasm_bindgen::preserve"
    )]
    pub testedTSAsDateTime: js_sys::Date,
}
```

However, I need to adopt it to hold an "undefined/null" JS value, so I tried this:

```rust
pub struct Params {
    #[serde(
        skip_deserializing
    )]
    pub testedTSAsDateTime: Option<js_sys::Date>,
}
```

It fails to compile:

> 100 | #[derive(Debug, Serialize, Deserialize, PartialEq, Clone)]
>     |                 ^^^^^^^^^ the trait `wasm_bindgen::JsCast` is not implemented for `std::option::Option<js_sys::Date>`

I tried various approaches to no avail. Could you give me any hint on how to approach this issue?

**Comment by RReverser** [comment]
Yeah not being able to apply `serde(with)` on containers is a general old issue in Serde design, see https://github.com/serde-rs/serde/issues/723. Unfortunately, I'm not sure if there's something we can do here...

Your best bet for now is probably to change the type of that field to `JsValue`, which will work with `preserve`, and then in your code you can manually check if it's `.is_undefined()` or, if not, cast it to `js_sys::Date`.

**Comment by RReverser** [comment]
> and then in your code you can manually check if it's `.is_undefined()` or, if not, cast it to `js_sys::Date`

You could also wrap this into a custom function compatible with `deserialize_with`. It would look roughly like this (untested):

```rust
fn deserialize_optional_date<'de, D: serde::Deserializer<'de>>(de: D) -> Result<Option<js_sys::Date>, D::Error> {
  let value: JsValue = serde_wasm_bindgen::preserve::deserialize(de)?;
  Ok(if value.is_undefined() {
    None
  } else {
    Some(value.dyn_into().map_err(|e| /* convert error */)?)
  })
}

/// ...

#[serde(deserialize_with = "deserialize_optional_date")]
pub testedTSAsDateTime: Option<js_sys::Date>,
```

Hope this helps.

**Comment by ronnybremer** [comment]
Thank you Ingvar, I will try both approaches and update my findings here for the benefit of others.

**Comment by murar8** [comment]
Just released a small crate to help work around the issue: https://crates.io/crates/serde_nested_with
It will generate the workaround module for you.

**Comment by ronnybremer** [comment]
> Your best bet for now is probably to change the type of that field to `JsValue`, which will work with `preserve`, and then in your code you can manually check if it's `.is_undefined()` or, if not, cast it to `js_sys::Date`.

I used this solution for now, it works perfectly. Either setting the JsValue field to JsValue::NULL or a date.dyn_into().

**Comment by murar8** [comment]
> Thats amazing, thank you for your help! I have a few structs which do not require "skip_deserialize" so for those I will test the new crate.

I updated the crate to support additional attributes, would be nice if you could give it a shot.

**Comment by ronnybremer** [comment]
> > Thats amazing, thank you for your help! I have a few structs which do not require "skip_deserialize" so for those I will test the new crate.
> 
> I updated the crate to support additional attributes, would be nice if you could give it a shot.

This is great! I am using the following struct statement and it works like a charm:
```rust
struct TestStruc {
    #[serde_nested(sub = "js_sys::Date", serde(with = "serde_wasm_bindgen::preserve"))]
    #[serde(skip_deserializing)]
    pub planningFinalizedTSAsDateTime: Option<js_sys::Date>,
}
```

Thank you again, this is amazingly helpful and hopefully will find many users besides me.

@RReverser Maybe this could be added to the README?

**Comment by RReverser** [comment]
It's not really serde-wasm-bindgen-specific, I'd rather suggest opening a PR against Serde's own docs so that it would be on https://serde.rs/.

**Comment by RReverser** [comment]
Off-topic, but I'm curious @ronnybremer, in examples like

```rs
pub struct Params {
    #[serde(
        skip_deserializing,
        default = "js_sys::Date::new_0",
        with = "serde_wasm_bindgen::preserve"
    )]
    pub testedTSAsDateTime: js_sys::Date,
}
```

do you really need `skip_deserializing` on field-by-field basis? The name "params" seems to suggest that it only goes one direction and never needs to be deserialized, so maybe you can omit `derive(Deserialize)` altogether?

**Comment by ronnybremer** [comment]
> do you really need `skip_deserializing` on field-by-field basis? The name "params" seems to suggest that it only goes one direction and never needs to be deserialized, so maybe you can omit `derive(Deserialize)` altogether?

The example is misleading, for sure. I have a large struct coming in from Json via a Rest call, deserialized with Serde. However, I would need to add a few calculated fields to the structure before passing it onto JS. Like converting a UNIX timestamp into a JsDate. Since those fields are not coming form the server, Serde would complain and hence I skip them during deserialization.
