### ISSUE TITLE
BTreeMap is failing to serialize?

### ISSUE THREAD

**Issue by zaphar** [RReverser/serde-wasm-bindgen#67]
I have been slowly moving over my stuff from the json serialization to this in a wasm project I have. While doing so I came across this issue.

I have a struct with a field of type `BTreeMap<String, u32>` which is always serializing as an empty map `{}` no matter what is in it. A minimal example is below:

```rust
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct State {
  recipe_counts: BTreeMap<String, u33>,
}
```

In my console logs I see the following:

```
DEBUG state=AppState { recipe_counts: {"baked_macaroni_cheese.txt": 1, "beef_broccoli_stir_fry.txt": 0} }
```

While after serialization in my logs I see:

```
state=JsValue( Object( { "recipe_counts":{ } } ) )
```

I am using version: `├── serde-wasm-bindgen v0.6.5`

It's not clear to me if I'm doing something wrong or if this is a bug.

**Comment by RReverser** [comment]
That's a problem of logging you're using.

The map is there, it's just not expanded when trying to print the value from Rust side, as it's Debug representation only has basic JS value support. If you print it on the JS side, or by calling to `console.log`, you should see the actual values.

**Comment by zaphar** [comment]
@RReverser I added the logging because I couldn't see the values in the indexeddb  object store where I was storing it either. I was testing stuff and it didn't seem like the values in the indexed db were correct. I've tested as you suggested and it does appear that the map is there.

Now to figure out if it's still there in indexed db as well. Thanks for the assistance!

**Comment by RReverser** [comment]
Hm I don't have much experience with IDB, but something that might be worth checking is whether it supports JS Maps at all. If not, you might need to enable the `serialize_maps_as_objects` option.

**Comment by zaphar** [comment]
Turns out it does not. Thanks again for the assist. It's funny what shakes out when you try to swap libraries out for new ones. :-D
