### ISSUE TITLE
Support JsValue serialization

### ISSUE THREAD

**Issue by spoutn1k** [RReverser/serde-wasm-bindgen#69]
Thank you for the great crate !

I am facing an issue and I'm not sure if it makes sense, but I have an object that contains some `web_sys` types, that essentially are JsValues. I was expecting to plug and play `serde-wasm-bindgen`, but the code would not compile because JsValue cannot be serialized as JsValue :/ Is it possible to make this happen ?

**Comment by RReverser** [comment]
This is covered in the README. https://github.com/RReverser/serde-wasm-bindgen#preserving-javascript-values

**Comment by spoutn1k** [comment]
Ok, so I have to create a struct for this ? My type is a tuple, I cannot use it directly ?

**Comment by RReverser** [comment]
If you mean that the `JsValue` is inside a tuple, then yes, it's currently not possible to apply `serde(with)` on nested types: https://github.com/serde-rs/serde/issues/723
